<?php
/**
 * Fontis Australia Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @author     Chris Norton
 * @copyright  Copyright (c) 2008 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <ul id="payment_form_<?=$this->getMethodCode()?>" style="display:none">
        <li>
            <div class="input-box">
			<style type="text/css">
			<!--
			table.bpay{
				width: 200px;
				font-family: Arial, Helvetica, sans-serif;
				background-color: #FFFFFF;
				margin: 0px;
				border: 2px solid #10204B;
				padding: 6px;
			}
			td.bpayLogo {
				width: 42px;
				border: 2px solid #142C61;
			}
			.bpayLogo img {
				margin: 12px;
			}
			td.customerReferenceBox {
				border: 2px solid #142C61;
				padding: 0px 8px;
				height: 54px;
				width: 158px;
			}

			.customerReferenceBoxText {
				font-size: 13px;
				text-transform: capitalize;
				color: #142C61;
				white-space: nowrap;
				line-height: 22px;
				font-weight: normal;
			}

			.billerTextHeading {
				font-size: 11px;
				text-transform: capitalize;
				color: #142C61;
				white-space: nowrap;
				line-height: 20px;
				font-weight: bold;	
			}
			.billerText{
				font-size: 11px;
				color: #142C61;
			}
			-->
			</style>
			<div align="left">
			<table border="0" cellpadding="0" cellspacing="0" class="bpay">
			<tr> 
				<td width="1%" class="bpayLogo"><img src="http://www.bpay.com.au/images/bpay.jpg" width="51" height="82" /></td>
				<td class="customerReferenceBox"> 
					<p class="customerReferenceBoxText">
					<?if ($this->getMethod()->getBillerCode()):?>
						<?=$this->__('<b>Biller Code</b>: %s', $this->getMethod()->getBillerCode())?><br />
					<?endif;?>
					<?if ($this->getMethod()->getRef()):?>
						<?=$this->__('<b>Ref</b>: %s', $this->getMethod()->getRef())?><br />
					<?endif;?>
					</p>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<p class="billerTextHeading">Telephone & Internet Banking – BPAY&reg;</p>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<p class="billerText">
					Contact your bank or financial institution to make this
					payment from your cheque, savings, debit, credit card
					or transaction account. More info: www.bpay.com.au
					</p>
				</td>
			</tr>
			</table>
			</div>
            <!--
            	<div style="border:1px solid blue; padding:8px;">
	            	<img src="http://localhost/magento/bpay_portrait_small.gif" width="85" height="120" style="float:left;border:2px solid blue;" />
	            	<div style="height:120px; border:2px solid blue; background:white; margin-left:95px;">
		            	<p style="margin: 10px; font-size:24px; ">
		                <?if ($this->getMethod()->getBillerCode()):?>
		                    <span style="margin-bottom:1em"><?=$this->__('<b>Biller Code</b>: %s', $this->getMethod()->getBillerCode())?></span><br />
		                <?endif;?>
		                <?if ($this->getMethod()->getRef()):?>
		                    <span><?=$this->__('<b>Ref</b>: %s', $this->getMethod()->getRef())?></span><br />
		                <?endif;?>
		                </p>
	                </div>
	                <div style="border: 2px solid blue; background: white; margin-top: 6px; font-size:18px; padding: 6px;">
	                <p><b>Telephone & Internet Banking – BPAY&reg;</b><br />
					Contact your bank or financial institution to make this
					payment from your cheque, savings, debit, credit card
					or transaction account. More info: www.bpay.com.au</p>
					</div>
				</div>
			-->
            </div>
        </li>
    </ul>
</fieldset>
